version: '2'

services:
  lanchonete:
    image: lanchonete
    build:
      context: ./Lanchonete
      dockerfile: Dockerfile
    expose:
      - "57700"

  proxy:
    build:
      context: ./Nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
    links:
     - lanchonete
